apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: pod
spec:
  containers:
  - image: centos:7
    imagePullPolicy: IfNotPresent
    name: pod
    resources: {}
    stdin: true
    stdinOnce: true
    terminationMessagePath: /dev/termination-log
    tty: true
